Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.boot_timeout = 1000

  
  # Configure memory and CPU settings
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 2
    vb.memory = 4096
    vb.customize ["modifyvm", :id, "--vram", "16"]
    # See https://github.com/hashicorp/vagrant/issues/11777
    # and https://stackoverflow.com/questions/38463579/vagrant-hangs-at-ssh-auth-method-private-key
    vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
    vb.customize ["modifyvm", :id, "--uartmode1", "file", File::NULL]
  end

  config.vm.provision "docker"

  config.vm.provision "bootstrap", type: "shell" do |shell|
      shell.path = "bootstrap.sh"
  end
end